### PR TITLE
build: fix breaking 1.8.3 build

### LINKED ISSUE #638: runtime: Kata runtime fails to build with go 1.8.3
# Description of problem
Build and install of Kata runtime fails

# Expected result
Successfully built the Kata runtime

# Actual result
```
runtime]# make && sudo -E PATH=$PATH make install
     CLEAN   clean
     GENERATE cli/config-generated.go
     CONFIG  data/kata-collect-data.sh
kata-runtime - version 1.2.0 (commit ed6f715ae6d46171c170c98909656539005766e3)

• architecture:
	Host: x86_64
	golang: amd64
	Build: amd64

• golang:
	go version go1.8.3 linux/amd64

• Summary:

	destination install path (DESTDIR)    : /
	binary installation path (BINDIR)     : /usr/local/bin
	binaries to install                   :
	 - /usr/local/bin/kata-runtime
	 - /usr/local/bin/data/kata-collect-data.sh
	config to install (CONFIG)            : cli/config/configuration.toml
	install path (CONFIG_PATH)            : /usr/share/defaults/kata-containers/configuration.toml
	alternate config path (SYSCONFIG)     : /etc/kata-containers/configuration.toml
	hypervisor path (QEMUPATH)            : /usr/bin/qemu-lite-system-x86_64
	assets path (PKGDATADIR)              : /usr/share/kata-containers
	proxy+shim path (PKGLIBEXECDIR)       : /usr/libexec/kata-containers

     BUILD   /home/nitesh/TST/kata/src/github.com/kata-containers/runtime/kata-runtime
# github.com/kata-containers/runtime/virtcontainers
../virtcontainers/agent.go:94: cannot use kataAgent literal (type *kataAgent) as type agent in return argument:
	*kataAgent does not implement agent (wrong type for init method)
		have init("github.com/kata-containers/runtime/vendor/golang.org/x/net/context".Context, *Sandbox, interface {}) error
		want init("context".Context, *Sandbox, interface {}) error
make: *** [Makefile:331: /home/nitesh/TST/kata/src/github.com/kata-containers/runtime/kata-runtime] Error 
```

### PR DESCRIPTION
**Pull request by WeiZhang555**
Fixes #638

Latest kata-runtime can't build with golang 1.8.3, fix it for backward compatibility.

Signed-off-by: Wei Zhang <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Golang version is bumped in another PR: https://github.com/kata-containers/runtime/pull/643

**Comment by jodh-intel** [comment]
Nice!

lgtm

**Comment by jodh-intel** [comment]
Ugh - another Clear Linux guest kernel crash on 16.04 CI:

```
time="2018-08-29T12:16:37.88774631Z" level=info msg="[    5.065088] run queue from wrong CPU 2, hctx active
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.888305717Z" level=info msg="[    5.065371] CPU: 2 PID: 205 Comm: kworker/2:1H Not tainted 4.14.51-135.container #1
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.88874082Z" level=info msg="[    5.065946] Workqueue: kblockd blk_mq_run_work_fn
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.889037597Z" level=info msg="[    5.066047] Call Trace:
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.889425584Z" level=info msg="[    5.066047]  dump_stack+0x5c/0x81
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.889854915Z" level=info msg="[    5.066047]  __blk_mq_run_hw_queue+0xc5/0xd0
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.890201577Z" level=info msg="[    5.066047]  process_one_work+0x110/0x320
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.890556646Z" level=info msg="[    5.066047]  worker_thread+0x42/0x430
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.890887844Z" level=info msg="[    5.066047]  kthread+0xf2/0x130
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.891281248Z" level=info msg="[    5.066047]  ? process_one_work+0x320/0x320
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.891711079Z" level=info msg="[    5.066047]  ? kthread_create_on_node+0x40/0x40
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.892094479Z" level=info msg="[    5.066047]  ? do_page_fault+0x2d/0x90
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
time="2018-08-29T12:16:37.892418472Z" level=info msg="[    5.066047]  ret_from_fork+0x35/0x40
" name=kata-proxy pid=6966 sandbox=a49ca4fbae25bf0f6b4f782c6627320764b474135f965d5f6c4f03244d485bbd source=agent
```

/cc @devimc, @grahamwhaley, @jcvenegas, @miguelinux.

**Comment by jodh-intel** [comment]
The first guest kernel crash I noticed is on #585.

**Comment by WeiZhang555** [comment]
CI passed. PTAL @jodh-intel @sboeuf @bergwolf

**Comment by bergwolf** [comment]
LGTM

**Comment by bergwolf** [comment]
Well, `pullapprove` doesn't recognize my approval. I'm going to ignore it as well >.<

**Comment by sboeuf** [comment]
@WeiZhang555 please backport to stable branches.

**Comment by WeiZhang555** [comment]
branch `stable-1.2` doesn't have same issue, this issue is introduced by opentracing feature.

**Comment by sboeuf** [comment]
@WeiZhang555 thanks for the feedback. So no need to backport neither to 1.1 nor to 1.2.
